### ISSUE TITLE
write_resultstofile function

### ISSUE THREAD

**Issue by joejoeyjoseph** [codenamenikky/CFARS_SS#2]
The function `write_resultstofile` called in 

> CFARS_SS_Phase1_Analysis.py 

cannot be used correctly. 

Even by adding `from DataParsingResults import write_resultstofile` in 

> CFARS_SS_Phase1_Analysis.py 

the function still does not work, because `write_resultstofile` takes 4 arguments in 

> DataParsingResults.py

instead of taking 2 arguments in the master code.

**Comment by codenamenikky** [comment]
@joejoeyjoseph the `write_resultstofile` in CFARS_SS_Phase1_Analysis.py does take 4 args the intent is to send dataframe to print, the worksheet to print, row start , and column start. 

i changed the writeresultstofile in the DataParsingResults.py given i didn't intend to pass the row number and column number for that. let me know if it makes sense. I understand that changing the functions between the modules is not ideal and will fix it for the future.

**Comment by codenamenikky** [comment]
I am closing this issue please contact me through email and we can schedule a meeting to discuss if you are still having issues for running this.
