### ISSUE TITLE
Data at different heights in the same data file

### ISSUE THREAD

**Issue by joejoeyjoseph** [codenamenikky/CFARS_SS#3]
I wonder if we have data of different heights, say, data at 50 and 80 m, in the same csv or Excel file, how would the `Configuration_template.xlsx` and the master Python code handle the errors at different levels?

**Comment by codenamenikky** [comment]
The configuration file is only looking for one Ref anemometer so I think the intent is to choose the reference height anemometer we want to use. if you have more data in your input file and you don't provide a configuration column for those columns the script essentially ignores them.
